import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
import { RightSidebar, LeftSidebar, BottomNav } from '@/components/common'
import { sataoshi } from '../font-config'
import { ThemeProvider } from '@/components/theme-provider'
import SessionProvider from '@/components/session-provider'
import { getServerSession } from 'next-auth'
import { redirect } from 'next/navigation'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession()
  console.log('session', session)
  if (!session || !session.user) {
    redirect('/sign-in')
  }
  return (
    <html lang='en'>
      <SessionProvider session={session}>
        <ThemeProvider attribute='class' defaultTheme='light' enableSystem>
          <body className={sataoshi.className}>
            {/* <TopNav /> */}
            <main>
              <LeftSidebar />
              <section className='' id='base-container'>
                <div className='w-full max-w-4xl'>{children}</div>
              </section>
              <RightSidebar />
            </main>
            <BottomNav />
          </body>
        </ThemeProvider>
      </SessionProvider>
    </html>
  )
}
