import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
import { RightSidebar, LeftSidebar, BottomNav } from '@/components/common'
import { sataoshi } from '../font-config'
import { ThemeProvider } from '@/components/theme-provider'
import SessionProvider from '@/components/session-provider'
import { getServerSession } from 'next-auth'
import { redirect } from 'next/navigation'
import { TopNav } from '@/components/common'
import Footer from '@/components/common/footer'
import { authOptions } from '@/lib/auth'
import { getSingleUser } from '@/lib/actions/user-action'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession(authOptions)
  if (!session || !session.user) {
    redirect('/sign-in')
  }
  const { ok, data } = await getSingleUser(session!.user.id)

  return (
    <html lang='en'>
      <SessionProvider session={session}>
        <ThemeProvider attribute='class' defaultTheme='dark' enableSystem>
          <body className={sataoshi.className}>
            <main className='flex justify-between'>
              <LeftSidebar />
              <section className='flex-1 flex justify-center px-4' id='base-container'>
                <TopNav />
                <div className='w-full max-w-2xl pb-40 max-md:pt-24 pt-32'>{children}</div>
              </section>
              <RightSidebar />
            </main>
            <Footer />
            <BottomNav />
          </body>
        </ThemeProvider>
      </SessionProvider>
    </html>
  )
}
